---

# Prepare system
- name: Ensure there is neo-go group
  ansible.builtin.group:
    name: "{{ neogo__group }}"
    system: True
    state: 'present'

- name: Ensure there is neo-go user
  ansible.builtin.user:
    name: "{{ neogo__user }}"
    group: "{{ neogo__group }}"
    password: !
    shell: /usr/sbin/nologin
    home: "{{ neogo__data_dir }}"
    system: True
    state: 'present'

- name: Ensure data directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ neogo__user }}"
    group: "{{ neogo__group }}"
    mode: '0750'
  with_items:
    - "{{ neogo__data_dir }}"

- name: Ensure configuration directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "root"
    group: "{{ neogo__group }}"
    mode: '0750'
  with_items:
    - "{{ neogo__conf_dir }}"

- include: download_binary.yml
  when: not (neogo__use_compose | bool)

- include: prepare_wallets.yml
  when: >
    (neogo__unlock_wallet | bool) or
    (neogo__stateroot_unlock_wallet | bool) or
    (neogo__oracle_unlock_wallet | bool)

- include: prepare_tls.yml
  when: neogo__tls_enabled | bool

- name: Prepare NeoGo config for {{ neogo__network }}
  ansible.builtin.template:
    src: 'protocol.network.yml.j2'
    dest: "{{ neogo__conf_dir }}/protocol.{{ neogo__network }}.yml"
    owner: 'root'
    group: "{{ neogo__group }}"
    mode: '0640'
  notify:
    - Restart neogo{{ neogo__instance }} service

- name: Get uid for neo-go user
  ansible.builtin.getent:
    database: passwd
    key: "{{ neogo__user }}"

- name: Get gid for neo-go user
  ansible.builtin.getent:
    database: group
    key: "{{ neogo__group }}"

- name: Prepare docker-compose for {{ neogo__network }}
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: "{{ neogo__conf_dir }}/docker-compose.yml"
    owner: 'root'
    group: "{{ neogo__group }}"
    mode: '0640'
  when: neogo__use_compose | bool
  notify:
    - Restart neogo{{ neogo__instance }} service

- name: Copy regular systemd unit file
  ansible.builtin.template:
    src: "neogo-n3.service.bin.j2"
    dest: "/etc/systemd/system/neogo{{ neogo__instance }}.service"
  when: not (neogo__use_compose | bool)
  notify:
    - Restart neogo{{ neogo__instance }} service

- name: Copy Docker systemd unit file
  ansible.builtin.template:
    src: "neogo-n3.service.compose.j2"
    dest: "/etc/systemd/system/neogo{{ neogo__instance }}.service"
  when: neogo__use_compose | bool
  notify:
    - Restart neogo{{ neogo__instance }} service

- name: Ensure NeoGo service runs
  ansible.builtin.systemd:
    name: "neogo{{ neogo__instance }}.service"
    state: 'started'
    enabled: yes
    daemon_reload: yes

- name: Force debops.ferm run
  include_role:
    name: debops.debops.ferm
  vars:
    ferm__dependent_rules:
      - "{{ neogo__ferm__dependent_rules }}"
  when: neogo__debops_ferm_import | bool
